#!/usr/bin/env bash
# optsweep.sh [DSP] [RATE] - build ONE ROM PER compiler-option variant, so a
# comparison is like-for-like.
#
# WHY ONE ROM EACH, and not all variants in one ROM (which was the first
# attempt): measured, that does not work. Inside a shared ROM, two variants
# that should be near-identical came out at 2200 and 954 cycles/sample - a
# 2.3x spread that no compiler flag explains. Where each variant's code and
# data land dominates everything else, so the only trustworthy comparison is
# the same DSP, in the same position, in separate ROMs.
#
# Run each ROM and read its number. Yes, that is one emulator launch per
# variant; it is the price of an answer you can believe.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Which faust? Homebrew's aborts on startup here (its LLVM wants libz3.4.16,
# which brew cleanup removed, and Homebrew refuses to rebuild LLVM on this
# machine - "Tier 3 configuration"). Fall back to the locally built compiler.
FAUST="${FAUST:-faust}"
( "$FAUST" --version >/dev/null 2>&1 ) || { echo "$(basename "$0"): no working faust" >&2; exit 1; }

DSP="${1:-demos/acid.dsp}"
SR="${2:-16000}"
: "${N64_INST:=$HOME/n64-toolchain}"
export N64_INST
FAUSTINC="$("$FAUST" --includedir 2>/dev/null || echo /usr/local/include)"
[ -d "$FAUSTINC/faust" ] || FAUSTINC=/usr/local/include

# name | faust flags | extra gcc flags
VARIANTS=(
  "base|-ftz 1|"
  "noftz||"
  "mapp|-ftz 1 -mapp|"
  "vec32|-ftz 1 -vec -lv 0 -vs 32|"
  "notrap|-ftz 1|-fno-trapping-math"
  "spconst|-ftz 1|-fsingle-precision-constant"
  "nt_sp|-ftz 1|-fno-trapping-math -fsingle-precision-constant"
  "O3|-ftz 1|-O3"
)

OUT="$HERE/build/optsweep"
rm -rf "$OUT"; mkdir -p "$OUT"
BASE="$(basename "$DSP" .dsp)"

for v in "${VARIANTS[@]}"; do
    nm="${v%%|*}"; rest="${v#*|}"
    ff="${rest%%|*}"; gf="${rest#*|}"
    id="v_$(printf '%s' "$nm" | tr -c 'A-Za-z0-9_' '_')"
    W="$OUT/$nm"
    mkdir -p "$W"
    cp "$HERE/tools/bench.c" "$W/bench.c"
    if ! "$FAUST" -lang c $ff -cn "$id" -o "$W/$id.c" "$DSP" 2>"$W/faust.err"; then
        echo "skip $nm: faust rejected '$ff'" >&2
        continue
    fi
    {
        echo '/* generated by tools/optsweep.sh */'
        echo 'typedef struct { const char *name; void *(*nw)(void); void (*in)(void*,int);'
        echo '  void (*cp)(void*,int,float**,float**); int (*no)(void*); int (*ni)(void*); } bench_entry;'
        echo "extern void *new$id(void);"
        echo "extern void init$id(void*,int);"
        echo "extern void compute$id(void*,int,float**,float**);"
        echo "extern int getNumOutputs$id(void*);"
        echo "extern int getNumInputs$id(void*);"
        echo "const bench_entry BENCH[] = {"
        echo "  { \"$nm\", new$id, init$id, compute$id, getNumOutputs$id, getNumInputs$id },"
        echo "};"
        echo "const int BENCH_COUNT = 1;"
    } > "$W/bench_table.c"

    cat > "$W/Makefile" <<MK
BUILD_DIR = obj
include \$(N64_INST)/include/n64.mk
N64_C_AND_CXX_FLAGS += -I$FAUSTINC -DBENCH_SR=$SR
N64_C_AND_CXX_FLAGS += -include faust/gui/CInterface.h
N64_C_AND_CXX_FLAGS += -Wno-error=unused-but-set-variable -Wno-error=unused-function
all: $nm.z64
.PHONY: all
OBJS = \$(BUILD_DIR)/bench.o \$(BUILD_DIR)/bench_table.o \$(BUILD_DIR)/$id.o
\$(BUILD_DIR)/$id.o: CFLAGS += $gf
\$(BUILD_DIR)/$nm.elf: \$(OBJS)
$nm.z64: N64_ROM_TITLE = "OPT $nm"
MK
    make -C "$W" -s >/dev/null
    cp "$W/$nm.z64" "$OUT/$BASE-$nm.z64"
    echo "  built $BASE-$nm.z64   faust[$ff]  gcc[$gf]"
done

echo
echo "optsweep: ROMs in build/optsweep/ - run each and compare its single number."
echo "Do NOT compare numbers taken from different DSPs or different sessions."
